project:
  type: website
  output-dir: docs

website:
  title: "Sam Csik"
  # reader-mode: true
  # repo-url: https://github.com/samanthacsik/samanthacsik.github.io
  # repo-actions: [edit, issue]
  site-url: https://samanthacsik.github.io/
  favicon: images/favicon/light-sage-chick.png
  google-analytics: 
    tracking-id: "G-LW03VL0YTS" #"UA-242992767-1"
    anonymize-ip: true
  navbar:
    title: false
    logo: images/logos/logo-transparent-dark.png
    logo-alt: "The name 'sam csik' written in green text. Above 'csik' is a dark green horizontal line, above which sits a green chick icon."
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: talks_workshops.qmd
        text: talks & workshops
      - href: courses.qmd
        text: courses
      - href: projects.qmd
        text: projects
      - posts.qmd
      - text: get in touch!
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/SamanthaCsik
            target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/samanthacsik/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:scsik@ucsb.edu
      - icon: github
        href: https://github.com/samanthacsik/samanthacsik.github.io
        target: _blank
  page-footer: 
    background: light
    left: Â© Copyright 2021, Samantha Csik
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true


