project:
  type: website
  output-dir: docs

website:
  title: "samantha csik"
  navbar:
    title: false
    logo: images/logos/nunito/creamBG_greenText/logo_nunito_cropped.png
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: talks_workshops.qmd
        text: talks & workshops
      - posts.qmd
      - resources.qmd
      - href: CV/SCsik_CV.pdf
        text: cv
      - icon: github
        href: https://github.com/samanthacsik
      - icon: twitter
        href: https://twitter.com/SamanthaCsik
  page-footer: 
    background: light
    left: 
      - "Copyright 2021, Samantha Csik"
    right: 
      - icon: github
        href: https://github.com/samanthacsik
      - icon: twitter
        href: https://twitter.com/SamanthaCsik
  reader-mode: true
  repo-url: https://github.com/samanthacsik/samanthacsik-quarto-website
  repo-actions: [edit, issue]

format:
  html:
    page-layout: full
    theme: 
      - green_theme.scss
    css: styles.css
    mainfont: Nunito
    toc: true


